### ISSUE TITLE
Lambda is failing due to unexpected token in response (WordPress instance being moved to HTTPS)

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-lambda-wordpress#12]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary

Migrating the WP instance to HTTPS as part of https://github.com/ProvidenceGeeks/website-frontend/issues/103 is now failing because the Node `http` module can't handle redirects (as we've currently implemented it)
![screen shot 2018-01-21 at 9 33 42 am](https://user-images.githubusercontent.com/895923/35195209-338ab5fc-fe8e-11e7-900a-81539e5f1b91.png)

Locally seeing the same thing
```shell
$ yarn run fetch
yarn run v1.3.2
$ node src/index.js
undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.resp.on (/Users/owenbuckley/Workspace/pvdgeeks.org/website-lambda-wordpress/src/index.js:170:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Will need to get this lambda to support HTTPS

**Comment by thescientist13** [comment]
Moving to use `require('https')` and now getting this
```shell
$ yarn run fetch
yarn run v1.3.2
$ node src/index.js
ERROR: Error: unable to verify the first certificate.
```

Looks like something is wrong with SSL configuration.  Running a test seems to confirm this
<img width="1099" alt="screen shot 2018-01-21 at 9 43 48 am" src="https://user-images.githubusercontent.com/895923/35195314-a1b8d47c-fe8f-11e7-864d-fe9d5d15430f.png">


> This server's certificate chain is incomplete. Grade capped to B.

**Comment by thescientist13** [comment]
Fixed!  It looks like during the configuration (for whatever reason) I neglected to add this line because it wasn't already in the conf file 😨 
https://medium.com/unicorn-supplies/ssl-for-aws-lightsail-wordpress-8053359a774f

> `SSLCertificateChainFile "/etc/letsencrypt/live/<domain>/fullchain.pem"`


Which is needed for our version of Apache since it is <= 2.4.8 per 
https://httpd.apache.org/docs/current/fr/mod/mod_ssl.html#sslcertificatechainfile
> **`SSLCertificateChainFile` is deprecated**
SSLCertificateChainFilehas become obsolete with version 2.4.8, when the directive SSLCertificateFilehas been extended to also support the intermediate CA certificates in the server certificate file.
```
$ apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Sep 18 2017 16:37:54
```

**Comment by thescientist13** [comment]
Now, running the SSL test we get an **A** 🎉 
<img width="1079" alt="screen shot 2018-01-21 at 9 59 44 am" src="https://user-images.githubusercontent.com/895923/35195467-e084c614-fe91-11e7-8dcc-d21cdcdecffb.png">

And running the Lambda locally we get a response 👍 
```
$ yarn run fetch
yarn run v1.3.2
$ node src/index.js
Successfully output data to ./output/wordpress-data.json
✨  Done in 0.95s.
```

**Comment by thescientist13** [comment]
Lambda is working 👍 🎉 
![screen shot 2018-01-21 at 10 02 17 am](https://user-images.githubusercontent.com/895923/35195499-8cac9732-fe92-11e7-80ec-7d56a4d20bda.png)
